import pynput
from pynput.keyboard import Key, Controller
import time

keyboard = Controller()

time.sleep(20)
keyboard.press('a')
keyboard.release('a')
keyboard.press('b')
keyboard.release('b')
keyboard.press('c')
keyboard.release('c')
keyboard.press('d')
keyboard.release('d')
keyboard.press('e')
keyboard.release('e')
keyboard.press('f')
keyboard.release('f')
keyboard.press('g')
keyboard.release('g')
keyboard.press('h')
keyboard.release('h')
keyboard.press('i')
keyboard.release('i')
keyboard.press('j')
keyboard.release('j')
keyboard.press('k')
keyboard.release('k')
keyboard.press('l')
keyboard.release('l')
keyboard.press('m')
keyboard.release('m')
keyboard.press('n')
keyboard.release('n')
keyboard.press('o')
keyboard.release('o')
keyboard.press('p')
keyboard.release('p')
keyboard.press('q')
keyboard.release('q')
keyboard.press('r')
keyboard.release('r')
keyboard.press('s')
keyboard.release('s')
keyboard.press('t')
keyboard.release('t')
keyboard.press('u')
keyboard.release('u')
keyboard.press('v')
keyboard.release('v')
keyboard.press('w')
keyboard.release('w')
keyboard.press('x')
keyboard.release('x')
keyboard.press('y')
keyboard.release('y')
keyboard.press('z')
keyboard.release('z')

input()